const data = [
    {
        "gender": "female",
        "title": "Mrs",
        "first": "Celine",
        "last": "Rødseth",
        "country": "Norway",
        "username": "yellowkoala710",
        "picture": "https://randomuser.me/api/portraits/women/10.jpg",
        "": "",
        "phone": "58742129",
        "email": "celine.rodseth@example.com"
    },
    {
        "gender": "male",
        "title": "Mr",
        "first": "Julian",
        "last": "Dunn",
        "country": "United Kingdom",
        "username": "yellowleopard451",
        "picture": "https://randomuser.me/api/portraits/men/34.jpg",
        "": "",
        "phone": "019467 47401",
        "email": "julian.dunn@example.com"
    },
    {
        "gender": "male",
        "title": "Mr",
        "first": "بنیامین",
        "last": "صدر",
        "country": "Iran",
        "username": "goldendog604",
        "picture": "https://randomuser.me/api/portraits/men/86.jpg",
        "": "",
        "phone": "036-42875663",
        "email": "bnymyn.sdr@example.com"
    },
    {
        "gender": "male",
        "title": "Mr",
        "first": "Johan",
        "last": "Brosch",
        "country": "Germany",
        "username": "tinypanda968",
        "picture": "https://randomuser.me/api/portraits/men/67.jpg",
        "": "",
        "phone": "0382-1812988",
        "email": "johan.brosch@example.com"
    },
    {
        "gender": "male",
        "title": "Mr",
        "first": "Arthur",
        "last": "Ginnish",
        "country": "Canada",
        "username": "sadfish773",
        "picture": "https://randomuser.me/api/portraits/men/72.jpg",
        "": "",
        "phone": "Z34 J20-9670",
        "email": "arthur.ginnish@example.com"
    },
    {
        "gender": "male",
        "title": "Mr",
        "first": "Ali",
        "last": "Keseroğlu",
        "country": "Turkey",
        "username": "redbutterfly421",
        "picture": "https://randomuser.me/api/portraits/men/38.jpg",
        "": "",
        "phone": "(445)-811-3284",
        "email": "ali.keseroglu@example.com"
    },
    {
        "gender": "male",
        "title": "Mr",
        "first": "Aloke",
        "last": "Banerjee",
        "country": "India",
        "username": "angrylion183",
        "picture": "https://randomuser.me/api/portraits/men/93.jpg",
        "": "",
        "phone": "9736567177",
        "email": "aloke.banerjee@example.com"
    },
    {
        "gender": "female",
        "title": "Mrs",
        "first": "Begüm",
        "last": "Nalbantoğlu",
        "country": "Turkey",
        "username": "orangebear321",
        "picture": "https://randomuser.me/api/portraits/women/60.jpg",
        "": "",
        "phone": "(435)-281-2155",
        "email": "begum.nalbantoglu@example.com"
    },
    {
        "gender": "female",
        "title": "Ms",
        "first": "Remedios",
        "last": "Diaz",
        "country": "Spain",
        "username": "purplebird361",
        "picture": "https://randomuser.me/api/portraits/women/34.jpg",
        "": "",
        "phone": "937-619-438",
        "email": "remedios.diaz@example.com"
    },
    {
        "gender": "male",
        "title": "Mr",
        "first": "Rico",
        "last": "Lemm",
        "country": "Germany",
        "username": "purplezebra740",
        "picture": "https://randomuser.me/api/portraits/men/10.jpg",
        "": "",
        "phone": "0840-8443618",
        "email": "rico.lemm@example.com"
    },
    {
        "gender": "female",
        "title": "Miss",
        "first": "Jasna",
        "last": "Babić",
        "country": "Serbia",
        "username": "organicwolf686",
        "picture": "https://randomuser.me/api/portraits/women/91.jpg",
        "": "",
        "phone": "033-3213-235",
        "email": "jasna.babic@example.com"
    },
    {
        "gender": "male",
        "title": "Mr",
        "first": "Hadrien",
        "last": "Leclerc",
        "country": "France",
        "username": "blackfish745",
        "picture": "https://randomuser.me/api/portraits/men/90.jpg",
        "": "",
        "phone": "04-74-74-55-40",
        "email": "hadrien.leclerc@example.com"
    },
    {
        "gender": "female",
        "title": "Ms",
        "first": "Ljiljana",
        "last": "Blažić",
        "country": "Serbia",
        "username": "greenbird257",
        "picture": "https://randomuser.me/api/portraits/women/64.jpg",
        "": "",
        "phone": "013-7937-586",
        "email": "ljiljana.blazic@example.com"
    },
    {
        "gender": "female",
        "title": "Ms",
        "first": "Julia",
        "last": "Nissen",
        "country": "Norway",
        "username": "heavypanda408",
        "picture": "https://randomuser.me/api/portraits/women/39.jpg",
        "": "",
        "phone": "33305765",
        "email": "julia.nissen@example.com"
    },
    {
        "gender": "female",
        "title": "Miss",
        "first": "Terry",
        "last": "Hansen",
        "country": "United States",
        "username": "angrygoose773",
        "picture": "https://randomuser.me/api/portraits/women/61.jpg",
        "": "",
        "phone": "(780) 579-1351",
        "email": "terry.hansen@example.com"
    },
    {
        "gender": "female",
        "title": "Ms",
        "first": "Thea",
        "last": "Anderson",
        "country": "New Zealand",
        "username": "lazybear903",
        "picture": "https://randomuser.me/api/portraits/women/35.jpg",
        "": "",
        "phone": "(955)-949-3436",
        "email": "thea.anderson@example.com"
    },
    {
        "gender": "male",
        "title": "Mr",
        "first": "Adán",
        "last": "Esquivel",
        "country": "Mexico",
        "username": "beautifulgorilla399",
        "picture": "https://randomuser.me/api/portraits/men/28.jpg",
        "": "",
        "phone": "(625) 819 8841",
        "email": "adan.esquivel@example.com"
    },
    {
        "gender": "female",
        "title": "Mrs",
        "first": "Jade",
        "last": "Gagnon",
        "country": "Canada",
        "username": "reddog221",
        "picture": "https://randomuser.me/api/portraits/women/92.jpg",
        "": "",
        "phone": "O45 U06-4136",
        "email": "jade.gagnon@example.com"
    },
    {
        "gender": "female",
        "title": "Mrs",
        "first": "Skye",
        "last": "Rog",
        "country": "Netherlands",
        "username": "blackwolf299",
        "picture": "https://randomuser.me/api/portraits/women/43.jpg",
        "": "",
        "phone": "(0796) 119989",
        "email": "skye.rog@example.com"
    },
    {
        "gender": "female",
        "title": "Mademoiselle",
        "first": "Celine",
        "last": "Louis",
        "country": "Switzerland",
        "username": "blackpeacock757",
        "picture": "https://randomuser.me/api/portraits/women/61.jpg",
        "": "",
        "phone": "077 008 90 13",
        "email": "celine.louis@example.com"
    },
    {
        "gender": "female",
        "title": "Ms",
        "first": "Ada",
        "last": "Buhalo",
        "country": "Ukraine",
        "username": "angrycat417",
        "picture": "https://randomuser.me/api/portraits/women/56.jpg",
        "": "",
        "phone": "(098) N73-9501",
        "email": "ada.buhalo@example.com"
    },
    {
        "gender": "male",
        "title": "Mr",
        "first": "Riley",
        "last": "Turner",
        "country": "United Kingdom",
        "username": "ticklishleopard396",
        "picture": "https://randomuser.me/api/portraits/men/36.jpg",
        "": "",
        "phone": "017683 51747",
        "email": "riley.turner@example.com"
    },
    {
        "gender": "female",
        "title": "Ms",
        "first": "Noémie",
        "last": "Sirko",
        "country": "Canada",
        "username": "blueswan403",
        "picture": "https://randomuser.me/api/portraits/women/89.jpg",
        "": "",
        "phone": "U55 Q56-8351",
        "email": "noemie.sirko@example.com"
    },
    {
        "gender": "female",
        "title": "Ms",
        "first": "Emma",
        "last": "Liu",
        "country": "Canada",
        "username": "silverbird316",
        "picture": "https://randomuser.me/api/portraits/women/30.jpg",
        "": "",
        "phone": "S65 N18-2611",
        "email": "emma.liu@example.com"
    },
    {
        "gender": "female",
        "title": "Mrs",
        "first": "Emilie",
        "last": "Gill",
        "country": "Canada",
        "username": "whitesnake867",
        "picture": "https://randomuser.me/api/portraits/women/49.jpg",
        "": "",
        "phone": "H64 C58-3707",
        "email": "emilie.gill@example.com"
    },
    {
        "gender": "male",
        "title": "Mr",
        "first": "Gabriel",
        "last": "Dahl",
        "country": "Germany",
        "username": "goldenostrich604",
        "picture": "https://randomuser.me/api/portraits/men/96.jpg",
        "": "",
        "phone": "0576-2325501",
        "email": "gabriel.dahl@example.com"
    },
    {
        "gender": "female",
        "title": "Miss",
        "first": "Julie",
        "last": "Rasmussen",
        "country": "Denmark",
        "username": "angryrabbit875",
        "picture": "https://randomuser.me/api/portraits/women/74.jpg",
        "": "",
        "phone": "42558823",
        "email": "julie.rasmussen@example.com"
    },
    {
        "gender": "male",
        "title": "Mr",
        "first": "Douglas",
        "last": "Morgan",
        "country": "United States",
        "username": "whiteduck989",
        "picture": "https://randomuser.me/api/portraits/men/46.jpg",
        "": "",
        "phone": "(979) 633-9540",
        "email": "douglas.morgan@example.com"
    },
    {
        "gender": "female",
        "title": "Miss",
        "first": "Eugenia",
        "last": "Ecker",
        "country": "Germany",
        "username": "silverbear552",
        "picture": "https://randomuser.me/api/portraits/women/20.jpg",
        "": "",
        "phone": "0023-2653645",
        "email": "eugenia.ecker@example.com"
    },
    {
        "gender": "female",
        "title": "Miss",
        "first": "Rose",
        "last": "Fortin",
        "country": "Canada",
        "username": "smallzebra115",
        "picture": "https://randomuser.me/api/portraits/women/51.jpg",
        "": "",
        "phone": "N94 Y29-3875",
        "email": "rose.fortin@example.com"
    },
    {
        "gender": "female",
        "title": "Miss",
        "first": "Camila",
        "last": "Richards",
        "country": "Australia",
        "username": "angrylion425",
        "picture": "https://randomuser.me/api/portraits/women/91.jpg",
        "": "",
        "phone": "04-0216-1997",
        "email": "camila.richards@example.com"
    },
    {
        "gender": "female",
        "title": "Ms",
        "first": "Kübra",
        "last": "Baturalp",
        "country": "Turkey",
        "username": "redlion787",
        "picture": "https://randomuser.me/api/portraits/women/24.jpg",
        "": "",
        "phone": "(546)-868-4531",
        "email": "kubra.baturalp@example.com"
    },
    {
        "gender": "male",
        "title": "Mr",
        "first": "Jakub",
        "last": "Strandheim",
        "country": "Norway",
        "username": "purpleleopard688",
        "picture": "https://randomuser.me/api/portraits/men/30.jpg",
        "": "",
        "phone": "66029246",
        "email": "jakub.strandheim@example.com"
    },
    {
        "gender": "female",
        "title": "Ms",
        "first": "Taiara",
        "last": "da Cruz",
        "country": "Brazil",
        "username": "tinymeercat607",
        "picture": "https://randomuser.me/api/portraits/women/87.jpg",
        "": "",
        "phone": "(72) 9336-7976",
        "email": "taiara.dacruz@example.com"
    },
    {
        "gender": "male",
        "title": "Mr",
        "first": "Kevin",
        "last": "Burton",
        "country": "United Kingdom",
        "username": "goldensnake214",
        "picture": "https://randomuser.me/api/portraits/men/78.jpg",
        "": "",
        "phone": "016977 12140",
        "email": "kevin.burton@example.com"
    },
    {
        "gender": "female",
        "title": "Mrs",
        "first": "Maxine",
        "last": "Torres",
        "country": "United States",
        "username": "orangeladybug222",
        "picture": "https://randomuser.me/api/portraits/women/15.jpg",
        "": "",
        "phone": "(723) 680-5187",
        "email": "maxine.torres@example.com"
    },
    {
        "gender": "male",
        "title": "Mr",
        "first": "Elias",
        "last": "Takala",
        "country": "Finland",
        "username": "yellowbutterfly698",
        "picture": "https://randomuser.me/api/portraits/men/23.jpg",
        "": "",
        "phone": "03-608-147",
        "email": "elias.takala@example.com"
    },
    {
        "gender": "male",
        "title": "Mr",
        "first": "Aaron",
        "last": "Jones",
        "country": "New Zealand",
        "username": "ticklishtiger486",
        "picture": "https://randomuser.me/api/portraits/men/53.jpg",
        "": "",
        "phone": "(364)-071-6956",
        "email": "aaron.jones@example.com"
    },
    {
        "gender": "female",
        "title": "Miss",
        "first": "Yvonne",
        "last": "Heymann",
        "country": "Germany",
        "username": "redmouse455",
        "picture": "https://randomuser.me/api/portraits/women/9.jpg",
        "": "",
        "phone": "0988-1970338",
        "email": "yvonne.heymann@example.com"
    },
    {
        "gender": "male",
        "title": "Mr",
        "first": "Niklas",
        "last": "Tolonen",
        "country": "Finland",
        "username": "redfrog893",
        "picture": "https://randomuser.me/api/portraits/men/52.jpg",
        "": "",
        "phone": "06-451-183",
        "email": "niklas.tolonen@example.com"
    },
    {
        "gender": "female",
        "title": "Mrs",
        "first": "María del Carmen",
        "last": "Samaniego",
        "country": "Mexico",
        "username": "beautifulfrog187",
        "picture": "https://randomuser.me/api/portraits/women/17.jpg",
        "": "",
        "phone": "(615) 058 0212",
        "email": "mariadelcarmen.samaniego@example.com"
    },
    {
        "gender": "female",
        "title": "Miss",
        "first": "Deeksha",
        "last": "Saniel",
        "country": "India",
        "username": "redelephant616",
        "picture": "https://randomuser.me/api/portraits/women/66.jpg",
        "": "",
        "phone": "9345152604",
        "email": "deeksha.saniel@example.com"
    },
    {
        "gender": "male",
        "title": "Mr",
        "first": "Rushil",
        "last": "Sheikh",
        "country": "India",
        "username": "blackpanda329",
        "picture": "https://randomuser.me/api/portraits/men/15.jpg",
        "": "",
        "phone": "8518990518",
        "email": "rushil.sheikh@example.com"
    },
    {
        "gender": "female",
        "title": "Miss",
        "first": "Begüm",
        "last": "Barbarosoğlu",
        "country": "Turkey",
        "username": "tinyduck628",
        "picture": "https://randomuser.me/api/portraits/women/93.jpg",
        "": "",
        "phone": "(467)-410-6304",
        "email": "begum.barbarosoglu@example.com"
    },
    {
        "gender": "female",
        "title": "Ms",
        "first": "یسنا",
        "last": "مرادی",
        "country": "Iran",
        "username": "bigswan202",
        "picture": "https://randomuser.me/api/portraits/women/30.jpg",
        "": "",
        "phone": "047-48738259",
        "email": "ysn.mrdy@example.com"
    },
    {
        "gender": "female",
        "title": "Mrs",
        "first": "Vanda",
        "last": "Harhalis",
        "country": "Ukraine",
        "username": "bigelephant200",
        "picture": "https://randomuser.me/api/portraits/women/11.jpg",
        "": "",
        "phone": "(068) C39-8264",
        "email": "vanda.harhalis@example.com"
    },
    {
        "gender": "male",
        "title": "Mr",
        "first": "شایان",
        "last": "رضایی",
        "country": "Iran",
        "username": "beautifulbird908",
        "picture": "https://randomuser.me/api/portraits/men/18.jpg",
        "": "",
        "phone": "055-11286509",
        "email": "shyn.rdyy@example.com"
    },
    {
        "gender": "female",
        "title": "Mrs",
        "first": "Jessica",
        "last": "Robinson",
        "country": "New Zealand",
        "username": "whitefrog142",
        "picture": "https://randomuser.me/api/portraits/women/65.jpg",
        "": "",
        "phone": "(445)-148-7513",
        "email": "jessica.robinson@example.com"
    },
    {
        "gender": "female",
        "title": "Mrs",
        "first": "Carolyn",
        "last": "Davidson",
        "country": "United States",
        "username": "redpeacock170",
        "picture": "https://randomuser.me/api/portraits/women/19.jpg",
        "": "",
        "phone": "(352) 535-0128",
        "email": "carolyn.davidson@example.com"
    },
    {
        "gender": "female",
        "title": "Ms",
        "first": "Tara",
        "last": "Dean",
        "country": "Australia",
        "username": "purpleswan835",
        "picture": "https://randomuser.me/api/portraits/women/87.jpg",
        "phone": "00-0364-6413",
        "email": "tara.dean@example.com"
    }
]